### ISSUE TITLE
K8SSAND-483 ⁃ Updating Statefulsets is broken when upgrading to 1.7.0

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/cass-operator#103]
**What happened?**
I created a CassandraDatacenter with cass-operator 1.6.0. I then updated to 1.7.0. cass-operator fails to apply StatefulSet changes. cass-operator logs this error:

`
{"level":"error","ts":1621959974.8570168,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"cassandradatacenter-controller","request":"default/labels","error":"StatefulSet.apps \"labels-labels-default-sts\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden","stacktrace":"github.com/go-logr/zapr.(_zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(_Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(_Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(_Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88"}
`

Note this part in particular:

```
Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"
```

This regression is due to the changes in #18 which change the `ServiceName` property of the StatefulSet.

cass-operator logs this error and does not continue with the reconciliation process. The Cassandra pods will remain running. If you try to change the CassandraDatacenter spec in such a way that would result in a change to the StatefulSet, the changes won't be applied.

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy cass-operator 1.6.0
1. Create a CassandraDatacenter

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: labels
spec:
  clusterName: labels
  size: 1
  storageConfig:
    cassandraDataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: standard
  serverType: cassandra
  serverVersion: 3.11.10
  serverImage: k8ssandra/cass-management-api:3.11.10-v0.1.24
  disableSystemLoggerSidecar: true
  dockerImageRunsAsCassandra: true
  podTemplateSpec:
    metadata:
      labels:
        env: dev
    spec:
      containers: []
```

1. Wait for the CassandraDatacenter to become ready
1. Upgrade the cass-operator deployment to 1.7.0
1. Check the cass-operator logs and you should find see the above error message

**Environment**

* Cass Operator version:

    `v1.7.0`
    
    **Anything else we need to know?**:The error occurs in the `CheckRackPodTemplate` function in `reconcile_racks.go`. This will impact any existing CassandraDatacenter that upgrades cass-operator.The bug will not impact new CassandraDatacenters installed with 1.7.0. I am inclined to say that we need to revert the changes in #18; however, doing so will introduce this problem for users who created new CassandraDatacenters with 1.7.0 and then go to upgrade. Given that we need to carefully consider how best to resolve this.

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-483) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-1.2.0,cass-operator-1.7.1
┆friendlyId: K8SSAND-483
┆priority: Highest
