### ISSUE TITLE
K8SSAND-513 ⁃ How to Locate transactional and search data on separate SSDs

### ISSUE THREAD

**Issue by ajgrande924** [k8ssandra/cass-operator#109]
Docs state that: 

```sh
Attention: It is critical that you locate DSE Cassandra transactional data and Solr-based DSE Search data on separate Solid State Drives (SSDs). Failure to do so will very likely result in sub-optimal search indexing performance.
```

link: https://docs.datastax.com/en/dse/6.8/dse-admin/datastax_enterprise/search/tuningIndexing.html#LocatetransactionalandsearchdataonseparateSSDs

Can this be configured with the cass-operator? If so can you share an example?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-513) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-513
┆priority: Medium

**Comment by burmanm** [comment]
One can add new storage paths to the deployed pods using the ``storageConfig/additionalVolumes``. For example:

```yaml
    additionalVolumes:
      - name: "dse-logs"
        mountPath: "/var/lib/dse/search"
        pvcSpec: 
          storageClassName: premium-ssd
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      - name: cassandra-commitlogs
        mountPath: /var/lib/cassandra/commitlog
        pvcSpec:
          storageClassName: premium-ssd
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
```

And then mount them under podTemplateSpec

```yaml
          volumeMounts:
            - mountPath: "/var/lib/cassandra/commitlog"
              name: "cassandra-commitlogs"
```

Example of those additionalMounts in use can be found from https://github.com/k8ssandra/cass-operator/blob/148b57fab4bd25920cd4400895cb494216f84cf0/tests/testdata/default-single-rack-single-node-addtional-volumes-dc.yaml

You need to set the ``config`` parameter to change where you want to store the data (those dse_solr parameters) and of course enable DSE search: https://github.com/k8ssandra/cass-operator/blob/148b57fab4bd25920cd4400895cb494216f84cf0/tests/testdata/solr-dc.yaml#L9-L10
