### ISSUE TITLE
K8SSAND-610 ⁃ Make live-/readiness probe settings configurable. 

### ISSUE THREAD

**Issue by cheapsolutionarchitect** [k8ssandra/cass-operator#124]
**What is missing?**

A facility that enables the configuration of the live-/readiness-probes  targeting the cassandra container.  This encompasses the listed settings (values are just for illustration)

* delay=15s 
* timeout=1s 
* period=15s
* success=1
* failure=3

Additionally making the stream_throughput_outbound_megabits_per_sec  in the cassandra.yaml configurable could be useful too.

**Why do we need it?**

When importing a large amount of data with the sstableloader  from within the k8ssandra/cassandra contaier the liveness test can fail a couple of times in a row due to high network load, although the pods  seem not to be affected and continue to import at high velocity. However, due to the probes failing, the pods will be restarted and the import aborted.

**Environment**

* Amazon EKS
* Cass Operator version:
* k8ssandra/cass-operator:v1.7.1

**Anything else we need to know?**:

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-610) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-610
┆priority: Medium

**Comment by jsanda** [comment]
>Additionally making the stream_throughput_outbound_megabits_per_sec in the cassandra.yaml configurable could be useful too.

This is already configurable when using cass-operator directly. It is not however configurable through k8ssandra. If you would like to make it configurable in k8ssandra, please create a separate ticket in the k8ssandra repo.

**Comment by burmanm** [comment]
Sorry for the late reply, but you can actually modify the liveness and readiness probes already. One can override all the PodTemplateSpec ones usually and in this case also. So if you set cassandra-container to have those liveness and readiness probes with different values, then cass-operator will use those and only set the missing values for that container. For example, the following will work:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc2
spec:
  clusterName: cluster2
  serverType: cassandra
  serverVersion: "4.0.1"
  managementApiAuth:
    insecure: {}
  size: 1
  podTemplateSpec:
    spec:
      containers:
        - name: "cassandra"
          livenessProbe:
            httpGet:
              path: /api/v0/probes/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/v0/probes/readiness
              port: 8080
            initialDelaySeconds: 35
            periodSeconds: 10
  storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  racks:
    - name: r1
  config:
    jvm-server-options:
      initial_heap_size: "512m"
      max_heap_size: "512m"
```

When the is pod created, this is what it looks like:

```
Containers:
  cassandra:
    Container ID:   containerd://1efe40136fa11c98d57f2f9f7fc3c1adcf3ee3bf843307771e854ec2aac4772a
    Image:          k8ssandra/cass-management-api:4.0.1
    Image ID:       docker.io/k8ssandra/cass-management-api@sha256:a17689dced9efcd7aa1b08462900f73adec1c5ed342b3f2318f8b1727ab04c48
    Ports:          9042/TCP, 9142/TCP, 7000/TCP, 7001/TCP, 7199/TCP, 8080/TCP, 9103/TCP, 9160/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Fri, 15 Oct 2021 12:00:52 +0300
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:8080/api/v0/probes/liveness delay=20s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8080/api/v0/probes/readiness delay=35s timeout=1s period=10s #success=1 #failure=3
    Environment:
      DS_LICENSE:               accept
      DSE_AUTO_CONF_OFF:        all
      USE_MGMT_API:             true
      MGMT_API_EXPLICIT_START:  true
      DSE_MGMT_EXPLICIT_START:  true
    Mounts:
      /config from server-config (rw)
      /etc/encryption/ from encryption-cred-storage (rw)
      /var/lib/cassandra from server-data (rw)
      /var/log/cassandra from server-logs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-vc897 (ro)
```

You can obviously also override just a single one (livenessProbe or readinessProbe)
