### ISSUE TITLE
K8SSAND-863 ⁃ Replacing nodes

### ISSUE THREAD

**Issue by github-vincent-miszczak** [k8ssandra/cass-operator#166]
**What did you do?**
Running a 3 nodes/1 node per AZ cluster on EKS with K8ssandra 1.3.1, I terminated a Kubernetes node in AZ `a` that was running a k8ssandra managed Cassandra pod, using a local volume. A new node was added to Kubernetes cluster after the old node died.

Because the volume is local the pod became unschedulable.

I added annotation `volumehealth.storage.kubernetes.io/health: inaccessible` on the PVC following https://github.com/datastax/cass-operator/pull/224. Nothing happened.

I removed the PVC manually. A new PVC and corresponding volume has been automatically created on the new node.The pod was rescheduled on the new node. The pod keeps Unhealhy. Logs show that it tries to contact the old pod, but it get a timeout as the old pod is dead 

```
io.netty.channel.ConnectTimeoutException: connection timed out: /10.220.35.109:7000
```

I edited the `cassandradatacenters.cassandra.datastax.com` resource filling `.spec.replaceNodes: ["k8ssandra-test-eu-west-1a-sts-0"]` following https://github.com/k8ssandra/cass-operator/blob/5ed8c3733b665524636e8526d9cb2d017e802b16/pkg/reconciliation/reconcile_racks.go#L1059 and https://github.com/k8ssandra/cass-operator/issues/78. Looking at the updated resource, I see that the values from `.spec.replaceNodes` has moved to `.status.nodeReplacements` as expected.  Nothing more happened (no log in the operator)

Querying cluster status using `nodetool` form an healthy pod, I can see

```
Datacenter: test
================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load        Tokens  Owns (effective)  Host ID                               Rack      
UJ  10.220.33.223  1.89 MiB    16      ?                 8619c8c9-6a6b-4d36-90a6-d3e9108823e5  eu-west-1a
UN  10.220.41.145  196.86 KiB  16      100.0%            2520f181-bd45-485e-a2ae-7fba73a5f3de  eu-west-1c
DN  10.220.35.109  177.62 KiB  16      100.0%            d082a3f7-29b8-4e5c-a204-e4fd99dbd497  eu-west-1a
UN  10.220.37.169  252.57 KiB  16      100.0%            ee679f79-2975-4517-90d6-8f0e2935c765  eu-west-1b
```

The new pod stays with Events 

```
 Warning  Unhealthy  46s (x177 over 30m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 500
```

`exec` in the new Cassandra pod and `ps auxwww` never show a try to start with `--replace_address`

Issuing `nodetool removenode d082a3f7-29b8-4e5c-a204-e4fd99dbd497` makes the new pod READY.
But the CassandraDatacenter resource is wrong, the `nodeReplacements` is empty but the status has kept the old ID, this is inconsistent.

```
  nodeReplacements: []
  nodeStatuses:
    k8ssandra-test-eu-west-1a-sts-0:
      hostID: d082a3f7-29b8-4e5c-a204-e4fd99dbd497

```

I also tried some variations around this, nothing triggered a replacement.

Given I got no log and there is no documentation, I'm a bit out of ideas and help would be welcome.

**Did you expect to see some different?**
I expected some documentation about replacing nodes.
I expected replacing dead nodes would be one of the most straightforward feature of an operator as this is something you have to do at some point.
I expected to get error messages or progress messages. I got none.

**Environment**
EKS 1.21, K8ssandra 1.3.1, cass-operator 1.7.1, local storage using rancher/local-path-provisioner:v0.0.20

* Manifests:

```
  cassandra:
        cassandraLibDirVolume:
          storageClass: local
        datacenters:
          - name: test
            size: 3
            racks:
              - name: eu-west-1a
                affinityLabels:
                  topology.kubernetes.io/zone: eu-west-1a
              - name: eu-west-1b
                affinityLabels:
                  topology.kubernetes.io/zone: eu-west-1b
              - name: eu-west-1c
                affinityLabels:
                  topology.kubernetes.io/zone: eu-west-1c
      stargate:
        enabled: false
      medusa:
        enabled: false
```

* Cass Operator Logs:

```
N/A
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-863) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-863
┆priority: Medium

**Comment by burmanm** [comment]
Is this the same as #110  ? That one was fixed in #141

**Comment by github-vincent-miszczak** [comment]
@burmanm, no because I'm not supposed to issue a `nodetool removenode` in the first place, but if I do, the result is inconsistent, so it's a bit related, but not the same at all.

**Comment by burmanm** [comment]
> I added annotation volumehealth.storage.kubernetes.io/health: inaccessible on the PVC following datastax/cass-operator#224. 
> Nothing happened

That annotation is not part of the normal Kubernetes, instead it's a vSphere Kubernetes distribution only feature. The replaceNode should have been the only thing to be used in this case.

**Comment by jsanda** [comment]
@github-vincent-miszczak can you share your cass-operator logs?

**Comment by github-vincent-miszczak** [comment]
I recreated a new cluster to be clean.
From a running cluster, I killed Kube node in AZ `a`.
State was 
```
k8ssandra-test-eu-west-1a-sts-0                     0/2     Pending   0          5m19s
k8ssandra-test-eu-west-1b-sts-0                     2/2     Running   0          15m
k8ssandra-test-eu-west-1c-sts-0                     2/2     Running   0          15m
```
Pod was pending because of local storage as expected:
```
Warning  FailedScheduling   57s (x6 over 6m56s)   default-scheduler   0/3 nodes are available: 1 node(s) had volume node affinity conflict, 2 node(s) didn't match Pod's node affinity/selector.
```

Then I issued `kubectl edit cassandradatacenters.cassandra.datastax.com test` and added `.spec.replaceNodes: ["k8ssandra-test-eu-west-1a-sts-0"]`, checking the file, I got then
```
 nodeReplacements:
  - k8ssandra-test-eu-west-1a-sts-0
  nodeStatuses:
    k8ssandra-test-eu-west-1a-sts-0:
      hostID: f41a0a54-9822-4bae-bfa0-94fec9c8a6b4
    k8ssandra-test-eu-west-1b-sts-0:
      hostID: 1f161ac4-8586-4972-be28-5819895379dd
    k8ssandra-test-eu-west-1c-sts-0:
      hostID: a78bd14a-52f8-4254-acc5-854cffa828d6
```

Nothing happened.

You'll find operator logs attached. It begins after it restarted (it was running on AZ `a` that I killed so it was rescheduled) up to after checking the replacement is in place in CassandraDatacenter and after waiting some time (nothing more happened by the time I wrote this comment)

**Log**:
[replace.log](https://github.com/k8ssandra/cass-operator/files/7100393/replace.log)
