### ISSUE TITLE
K8SSAND-918 ⁃ Updates to podTemplateSpec do not propagate to the statefulSet

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/cass-operator#177]
**Problem description**

If I make a change to the podTemplateSpec within the cassDC CR, I do not see the change propagate to the sts without manually deleting it.

**Reproducing**

For example, if I have a cassandra container defined like so within the `podTemplateSpec` field:

```
podTemplateSpec:
      metadata:
        creationTimestamp: null
spec:
        containers:
        - env:
          - name: LOCAL_JMX
            value: "no"
          name: cassandra
          resources: {}
```

I add `imagePullPolicy: IfNotPresent` to the container. This does not propagate without manually deleting the sts.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-918) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-918
┆priority: Medium
