### ISSUE TITLE
K8SSAND-962 ⁃ Investigate making the root file system in cassandra container read-only

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/cass-operator#199]
**Why do we need it?**
The root file system should be read-only for improved security. This is considered a best practice for security. 

#196 was created specifically for DSE. The goal for this ticket is to address both OSS Cassandra and DSE. If it turns out that there are substantially different changes required for Cassandra vs DSE, then they should be addressed in separate PRs.

Here is an example manifest that configures the `cassandra` container with a read-only root file system:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: test
  serverType: cassandra
  serverVersion: "4.0.0"
  systemLoggerImage:
  serverImage:
  size: 1
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  podTemplateSpec:
    spec:
      containers:
        - name: "cassandra"
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
        config:
    jvm-server-options:
      initial_heap_size: "800M"
      max_heap_size: "800M"
```

The `cassandra` goes into a crash loop with this in the log:

```
Starting Management API
cp: cannot create regular file '/opt/cassandra/conf/cassandra-env.sh': Read-only file system
cp: cannot create regular file '/opt/cassandra/conf/cassandra-rackdc.properties': Read-only file system
cp: cannot create regular file '/opt/cassandra/conf/cassandra.yaml': Read-only file system
cp: cannot create regular file '/opt/cassandra/conf/jvm11-server.options': Read-only file system
cp: cannot create regular file '/opt/cassandra/conf/jvm8-server.options': Read-only file system
cp: cannot create regular file '/opt/cassandra/conf/jvm.options': Read-only file system
cp: cannot create regular file '/opt/cassandra/conf/jvm-server.options': Read-only file system
cp: cannot create regular file '/opt/cassandra/conf/logback.xml': Read-only file system
```

**Environment**

* Cass Operator version:
v1.8.0

**Anything else we need to know?**:
We have already implemented a solution (or at least partial) in the k8ssandra Helm chart. Look at the `cassdc.yaml` template [here](https://github.com/k8ssandra/k8ssandra/blob/main/charts/k8ssandra/templates/cassandra/cassdc.yaml#L170). Here are the highlights:

* Add a `cassandra-config` volume to be used to `/etc/cassandra`
* The `base-config-init` init container copies out of box configs to `cassandra-config`
* The `server-config-init` init container (i.e., config builder) runs and writes files to the `server-config` volume 
* The `cassandra` container mounts `server-config` at `/config` 
* The `cassandra` container mounts `cassandra-config` at `/etc/cassandra`
* The entry point script of the `cassandra` container copies files from `/config` to `/etc/cassandra`

Again this what is already done in k8ssandra. We basically need to backport it.

```[tasklist]
### Fixes
- [ ] https://github.com/k8ssandra/cass-operator/issues/196
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-962) by [Unito](https://www.unito.io)
┆epic: Security Phase II
┆friendlyId: K8SSAND-962
┆priority: Medium
