### ISSUE TITLE
K8SSAND-976 ⁃ Direct updates to StatefulSet do not get reconciled

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/cass-operator#206]
**What happened?**
I stumbled onto this while helping a community member with some debugging. I suggested that the user change the heap of the management-api by setting an env var in the PodTemplateSpec. He had already directly updated the StatefulSet. I explained that the update should be made through the CassandraDatacenter. Updating the CassandraDatacenter but with a different value did not result in a StatefulSet update.

This was originally reported in https://github.com/k8ssandra/k8ssandra/issues/1136.

I set the env var `MGMT_API_HEAP_SIZE` to 64M directly in the StatefulSet. After the update completed I then set `MGMT_API_HEAP_SIZE` to 32M in the podTemplateSpec property of the CassandraDatacenter. No subsequent update was made. `MGMT_API_HEAP_SIZE` was left at 64M

**Did you expect to see something different?**
The StatefulSet should have been updated with `MGMT_API_HEAP_SIZE` being set to 32M. We can end up in a situation where desired state != actual state and it goes undetected by cass-operator.

**How to reproduce it (as minimally and precisely as possible)**:
Create a CassandraDatacenter:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc3
  namespace: k8ssandra-operator
spec:
  clusterName: dev
  config:
    jvm-server-options:
      initial_heap_size: 800M
      max_heap_size: 800M
  podTemplateSpec:
    spec:
      containers:
      - env:
        - name: MGMT_API_HEAP_SIZE
          value: 64M
        name: cassandra
  serverType: cassandra
  serverVersion: 4.0.0
  size: 1
  storageConfig:
    cassandraDataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: standard
```

After the Cassandra pod becomes ready directly update the podTemplateSpec of the StatefulSet by setting `MGMT_API_HEAP_SIZE` to 32M. The Cassandra pod will get recreated with the change. No further changes are applied by cass-operator. 

I restarted cass-operator to trigger another reconciliation thinking that was all that was necessary. It didn't help though. 

**Environment**

* Cass Operator version:

v1.8.0

**Anything else we need to know?**:
When constructing a new StatefulSet object we compute the hash of it and store it in the `cassandra.datastax.com/resource-hash` annotation. In the `CheckRackPodTemplate` method we construct a new StatefulSet based on the current CassandraDatacenter spec and compare the hash against the actual StatefulSet's hash. The hash hasn't change so cass-operator doesn't do anything.

I reviewed the StatefulSet controller code a bit to see what it does. It creates and manages a revision history via ControllerRevision objects. It stores a copy of the StatefulSet spec which I will exclude here for brevity, but here is what the rest of the object looks like:

```yaml
kind: ControllerRevision
metadata:
  annotations:
    cassandra.datastax.com/resource-hash: 09ESy/rZiZUfJ0ughdNEbitogNExcNhaQ6WuWSxSbj8=
  creationTimestamp: "2021-10-15T12:14:08Z"
  labels:
    app.kubernetes.io/managed-by: cass-operator
    cassandra.datastax.com/cluster: dev
    cassandra.datastax.com/datacenter: dc3
    cassandra.datastax.com/node-state: Ready-to-Start
    cassandra.datastax.com/rack: default
    controller.kubernetes.io/hash: 7657dd46f5
  name: dev-dc3-default-sts-7657dd46f5
  namespace: k8ssandra-operator
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: dev-dc3-default-sts
    uid: c966d457-b523-4692-bec4-88ae2b022cb1
  resourceVersion: "55912"
  uid: 9a11befc-35c7-4db5-99c8-394d006cbe42
revision: 3
```

Note the `controller.kubernetes.io/hash` label. Now here is the status of my StatefulSet:

```yaml
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: dev-dc3-default-sts-7657dd46f5
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updateRevision: dev-dc3-default-sts-7657dd46f5
  updatedReplicas: 1
```

The `currentRevision` is the name of the StatefulSet with the `controller.kubernetes.io/hash` appended. In addition to the hash that we compute and compare we should also keep track of currentRevision for each StatefulSet. If that values differs from what we have stored then we know we have an out of band change.

Since we create a StatefulSet per rack we need to track the revision for each. Similar to how the StatefulSet stores the revision in its status we can store the revision for each rack in the CassandraDatacenter status.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-976) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-976
┆priority: Medium
