### ISSUE TITLE
K8SSAND-1006 ⁃ Liveness and Readiness are missing from the server-system-logger container

### ISSUE THREAD

**Issue by zhimsun** [k8ssandra/cass-operator#220]
**What is missing?**

We deployed a CassandraDatacenter with the container `cassandra`. The operators created one more container `server-system-logger`, Liveness and Readiness are missing from the `server-system-logger` container.

**Environment**
Openshift 4.8

CR

```
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc2
spec:
  clusterName: cluster1
  serverType: dse
  serverVersion: "6.8.14"
  systemLoggerImage: "<imageRepository>"
  serverImage: "<imageRepository>"
  configBuilderImage: "<imageRepository>"
  managementApiAuth:
    insecure: {}
  size: 1
  resources:
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      cpu: 1
      memory: 4Gi

  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: nfs-client
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  dockerImageRunsAsCassandra: false
  podTemplateSpec:
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      initContainers:
      - name: server-config-init
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
      containers:
      - name: "cassandra"
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
  config:
    jvm-server-options:
      initial_heap_size: "800M"
      max_heap_size: "800M"
      additional-jvm-opts:
        # As the database comes up for the first time, set system keyspaces to RF=3
        - "-Ddse.system_distributed_replication_dc_names=dc2"
        - "-Ddse.system_distributed_replication_per_dc=3"
```

The sts description 

```
oc describe sts cluster1-dc2-default-sts
```

```
Name:               cluster1-dc2-default-sts
Namespace:          zen
CreationTimestamp:  Tue, 26 Oct 2021 09:40:06 -0700
Selector:           cassandra.datastax.com/cluster=cluster1,cassandra.datastax.com/datacenter=dc2,cassandra.datastax.com/rack=default
Labels:             app.kubernetes.io/managed-by=cass-operator
                    cassandra.datastax.com/cluster=cluster1
                    cassandra.datastax.com/datacenter=dc2
                    cassandra.datastax.com/rack=default
Annotations:        cassandra.datastax.com/resource-hash: MFxYV46UTcPFy/52bvamgbTmgjn965m2JgS5q0d7lXM=
Replicas:           1 desired | 1 total
Update Strategy:    RollingUpdate
  Partition:        0
Pods Status:        1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app.kubernetes.io/managed-by=cass-operator
                    cassandra.datastax.com/cluster=cluster1
                    cassandra.datastax.com/datacenter=dc2
                    cassandra.datastax.com/node-state=Ready-to-Start
                    cassandra.datastax.com/rack=default
  Service Account:  default
  Init Containers:
   server-config-init:
    Image:     
    Port:       <none>
    Host Port:  <none>
    Limits:
      cpu:     1
      memory:  256M
    Requests:
      cpu:     1
      memory:  256M
    Environment:
      POD_IP:                      (v1:status.podIP)
      HOST_IP:                     (v1:status.hostIP)
      USE_HOST_IP_FOR_BROADCAST:  false
      RACK_NAME:                  default
      PRODUCT_VERSION:            6.8.14
      PRODUCT_NAME:               dse
      DSE_VERSION:                6.8.14
      CONFIG_FILE_DATA:           {"cassandra-yaml":{},"cluster-info":{"name":"cluster1","seeds":"cluster1-seed-service"},"datacenter-info":{"graph-enabled":0,"name":"dc2","solr-enabled":0,"spark-enabled":0},"jvm-server-options":{"additional-jvm-opts":["-Ddse.system_distributed_replication_dc_names=dc2","-Ddse.system_distributed_replication_per_dc=3"],"initial_heap_size":"800M","max_heap_size":"800M"}}
    Mounts:
      /config from server-config (rw)
  Containers:
   cassandra:
    Image:       <imageRepository>
    Ports:       9042/TCP, 9142/TCP, 7000/TCP, 7001/TCP, 7199/TCP, 8080/TCP, 9103/TCP, 9160/TCP, 8609/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    Limits:
      cpu:     1
      memory:  4Gi
    Requests:
      cpu:      1
      memory:   4Gi
    Liveness:   http-get http://:8080/api/v0/probes/liveness delay=15s timeout=1s period=15s #success=1 #failure=3
    Readiness:  http-get http://:8080/api/v0/probes/readiness delay=20s timeout=1s period=10s #success=1 #failure=3
    Environment:
      DS_LICENSE:               accept
      DSE_AUTO_CONF_OFF:        all
      USE_MGMT_API:             true
      MGMT_API_EXPLICIT_START:  true
      DSE_MGMT_EXPLICIT_START:  true
    Mounts:
      /config from server-config (rw)
      /etc/encryption/ from encryption-cred-storage (rw)
      /var/lib/cassandra from server-data (rw)
      /var/log/cassandra from server-logs (rw)
   server-system-logger:
    Image:     <imageRepository> 
    Port:       <none>
    Host Port:  <none>
    Limits:
      cpu:     100m
      memory:  64M
    Requests:
      cpu:        100m
      memory:     64M
    Environment:  <none>
    Mounts:
      /var/log/cassandra from server-logs (rw)
  Volumes:
   server-config:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
   server-logs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
   encryption-cred-storage:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  dc2-keystore
    Optional:    false
Volume Claims:
  Name:          server-data
  StorageClass:  nfs-client
  Labels:        app.kubernetes.io/managed-by=cass-operator
                 cassandra.datastax.com/cluster=cluster1
                 cassandra.datastax.com/datacenter=dc2
                 cassandra.datastax.com/rack=default
  Annotations:   <none>
  Capacity:      10Gi
  Access Modes:  [ReadWriteOnce]
Events:
  Type    Reason            Age   From                    Message
  ----    ------            ----  ----                    -------
  Normal  SuccessfulCreate  79m   statefulset-controller  create Claim server-data-cluster1-dc2-default-sts-0 Pod cluster1-dc2-default-sts-0 in StatefulSet cluster1-dc2-default-sts success
  Normal  SuccessfulCreate  79m   statefulset-controller  create Pod cluster1-dc2-default-sts-0 in StatefulSet cluster1-dc2-default-sts successful
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1006) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1006
┆priority: Medium
