### ISSUE TITLE
K8SSAND-1060 ⁃ CassandraDatacenter  spec.config in body must be of type byte: "" 

### ISSUE THREAD

**Issue by DrissiReda** [k8ssandra/cass-operator#239]
**What happened?**

I cannot create a cassandra datacenter, I get the error:

```
CassandraDatacenter.cassandra.datastax.com "dcx" is invalid: spec.config: Invalid value: "": spec.config 
in body must be of type byte: "" 
```

The deployment works if I set `spec.config` to `random_string`. But then my configuration isn't used in my cassandra cluster. 

**Did you expect to see something different?**

I expect to be able to supply my own `cassandra.yaml` conf and jvm options.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy cass-operator, using this [crd](https://raw.githubusercontent.com/k8ssandra/cass-operator/master/config/crd/bases/cassandra.datastax.com_cassandradatacenters.yaml). 
And this [webhook](https://raw.githubusercontent.com/k8ssandra/cass-operator/master/config/webhook/manifests.yaml)

<details>

<summary> Create this datacenter </summary>

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dcx
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: 3.11.7
  managementApiAuth:
    insecure: {}
  size: 1
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: server-storage
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  config:
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: 800M
      max_heap_size: 800M
```

</details>

**Environment**

* Cass Operator version:

cass-operator:1.6.0

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T13:00:45Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

```

* Kubernetes cluster kind:

   kubeadm

* Cass Operator Logs:

No specific logs, the datacenter isn't created

Using the old

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1060) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1060
┆priority: Medium
