### ISSUE TITLE
K8SSAND-1113 ⁃ PVC is not used when deploying with the example config

### ISSUE THREAD

**Issue by Yuyan-Li** [k8ssandra/cass-operator#247]
**What happened?**

After creating a Cassandra cluster, everything is created as expected. But the data is not written into the PVCs. Inside the container I can see that the data is actually written to `/opt/cassandra/data/data`. This is because the default location is `$CASSANDRA_HOME/data/data` (can be seen [here](https://github.com/apache/cassandra/blob/9fe62b3e40147fda2cc081744bd375b04574aef7/conf/cassandra.yaml#L189)).

To write to the PVC one has to add these lines to the `cassandra.yaml`.

```
data_file_directories:
    - /var/lib/cassandra/data
hints_directory: /var/lib/cassandra/hints
commitlog_directory: /var/lib/cassandra/commitlog
cdc_raw_directory: /var/lib/cassandra/cdc_raw
saved_caches_directory: /var/lib/cassandra/saved_caches
```

**Did you expect to see something different?**
I expected the cass-operator to set all configs so that data is automatically written to the VolumeClaim. If that expectation was wrong then I would expect the example configuration to reflect that.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Cass Operator version:
cass-operator v1.5.0
* Kubernetes version information:
1.20
* Kubernetes cluster kind:
Openshift
* Manifests:

```
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: a-cassandra-cluster
  serverType: cassandra
  serverVersion: 3.11.7
  managementApiAuth:
    insecure: {}
  size: 3
  resources:
    requests:
      memory: 5Gi
      cpu: 3
    limits:
      memory: 5Gi
      cpu: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
  config:
    cassandra-yaml:
      num_tokens: 8
      authenticator: org.apache.cassandra.auth.AllowAllAuthenticator
      authorizer: org.apache.cassandra.auth.AllowAllAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: 2G
      max_heap_size: 2G
      additional-jvm-opts:
        - "-Dcassandra.system_distributed_replication_dc_names=dc1"
        - "-Dcassandra.system_distributed_replication_per_dc=3"
```

* Cass Operator Logs:
n/a

**Anything else we need to know?**:

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1113) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1113
┆priority: Medium
