### ISSUE TITLE
K8SSAND-1179 ⁃ [Question] What setttings should I set so I can use nodetool in remote machine ?

### ISSUE THREAD

**Issue by counter2015** [k8ssandra/cass-operator#262]
**What did you do?**

I install a cassandra cluster in k8s by cass-operator

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
  namespace: cassandra
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: "4.0.1"
  managementApiAuth:
    insecure: {}
  size: 3
  resource:
    requests:
      memory: 12Gi
      cpu: 3000m
    limits:
      memory: 12Gi
      cpu: 3000m
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: gp2
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
  config:
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
      enable_sasi_indexes: true
    jvm-server-options:
      initial_heap_size: 12G
      max_heap_size: 12G

```

I'm using `nodetool -h <pod-ip> snapshot` to backup keyspace.

It need to enable jmx remote port, in `cassandra-env.sh` it says

```

# jmx: metrics and administration interface
#
# add this if you're having trouble connecting:
# JVM_OPTS="$JVM_OPTS -Djava.rmi.server.hostname=<public name>"
#
# see
# https://blogs.oracle.com/jmxetc/entry/troubleshooting_connection_problems_in_jconsole
# for more on configuring JMX through firewalls, etc. (Short version:
# get it working with no firewall first.)
#
# Cassandra ships with JMX accessible *only* from localhost.  
# To enable remote JMX connections, uncomment lines below
# with authentication and/or ssl enabled. See https://wiki.apache.org/cassandra/JmxSecurity 
#
if [ "x$LOCAL_JMX" = "x" ]; then
    LOCAL_JMX=yes
fi
```

It seems that I should pass a enviroment variable `LOCAL_JMX` with any value except `yes`

But I can't find a way to pass it 

https://github.com/k8ssandra/cass-operator/blob/master/operator/example-cassdc-yaml/cassandra-3.11.x/example-cassdc-full.yaml

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

AWS eks

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1179) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1179
┆priority: Medium

**Comment by jsanda** [comment]
It's non-trivial to enable remote JMX. We do it in k8ssandra by configuring the CassandraDatacenter's `.spec.podTemplateSpec` property to set it up. Doing this is advanced and requires a fair bit of understanding of cass-operator's internals. 

Do you need remote access?

I execute nodetool locally within the pod as follows,

`kubectl exec -it <cassandra-pod> -c cassandra -- nodetool status`

**Comment by counter2015** [comment]
@jsanda Thanks your fast reply!

I'm trying to migrate data from exist single node cassandra to cluster by `nodetool snapshot` and `nodetool import`

Since the data is large and it's not a good way to download data to local , so I try to open remote jmx port .
In this way, I can make snapshot of single node in cluster pod.

Another hard way I found is copy data to local machine and upload it to new cluster.

**Comment by burmanm** [comment]
If there's access from new cluster to the old one, then you could do that nodetool snapshot + import from the new cluster's pod also. That way you don't have to import it to your own machine. And you wouldn't need that remote jmx in the new cluster.

**Comment by adutra** [comment]
There are in theory 2 steps involved to enable remote JMX access:

1. In CassandraDatacenter spec, modify `.spec.podTemplateSpec` and add a new environment variable to the main container: `LOCAL_JMX=no`. This will enable remote JMX.
2. However this will also enable JMX authentication, and that's where it gets tricky. You will also have to define, in each cassandra pod, a new file `jmxremote.password`  containing the credentials that you will then use when running `nodetool` from a remote pod. To create this file, you would typically define a new init container in `.spec.podTemplateSpec` with a shell script that creates the file on a shared volume mount also accessible from the main container that runs Cassandra.

**Comment by adutra** [comment]
There is an alternative to step 2 above: forcibly disable JMX authentication. Add the following snippet to your CassandraDatacenter spec:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: mycluster
  config:
    cassandra-env-sh:
      additional-jvm-opts:
        - -Dcom.sun.management.jmxremote.authenticate=false
```

This should get you unauthenticated remote JMX calls. Use at your own risk :-)
