### ISSUE TITLE
K8SSAND-1180 ⁃ How do we gracefully increase storage capacity via cass-operator while Cass Datacenter, Statefulset etc are in service with incoming workloads

### ISSUE THREAD

**Issue by mparikhcloudbeds** [k8ssandra/cass-operator#263]
Following the below thread, wanted to get an update:
https://community.datastax.com/questions/12269/index.html

Environment:

* AWS EKS and AWS EBS
* Cass-Operator : 1.9
* Server Image : DSE 6.8.18 and/or OSS 3.11.11

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1180) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1180
┆priority: Medium

**Comment by burmanm** [comment]
Hi, does your PV provider support PVC volume expansion?

**Comment by mparikhcloudbeds** [comment]
> Hi, does your PV provider support PVC volume expansion?

@burmanm - Yes, the storage class that we are using has the following property.
`allowVolumeExpansion: true`

**Comment by mparikhcloudbeds** [comment]
@burmanm - Following up to see if there's an update on this?

**Comment by burmanm** [comment]
Hey, sorry. The process of expanding a PVC with StatefulSets is a bit tricky and involves manual operations (restriction of Kubernetes). Sadly my local instance did not support the feature, but I'll try to create an example shortly with documented steps.

**Comment by mparikhcloudbeds** [comment]
thnx @burmanm .

Is this something on the roadmap of cass-operator project?

**Comment by bradfordcp** [comment]
It's a feature we would like to see, but unfortunately has not been scheduled yet. We have identified the steps to resolve the issue, but it will require a bit of time to implement.

**Comment by counter2015** [comment]
> Hey, sorry. The process of expanding a PVC with StatefulSets is a bit tricky and involves manual operations (restriction of Kubernetes). Sadly my local instance did not support the feature, but I'll try to create an example shortly with documented steps.

@burmanm Could you provide more details about this?
I have a 4 node cluster and there disk usage is almost full.
A workaround is to add nodes in cluster, and the data will rebalanced, and cleanup auto.
But it is a waste of cpu and memory resources.

**Comment by discostur** [comment]
@counter2015 you can easily upgrade your storage manually:

* set new storage capacity in your PVC
* restart the cassandra pods one by one

Then, your PVCs should automatically get resized by your storage csi.

**Comment by counter2015** [comment]
@discostur I am not sure if the PVC capactity will be changed by operator after I edit datacenter yaml file.
Finally, I incresed storage capacity by creating a new datacenter and migrating data from old dc1 to new dc2.

**Comment by discostur** [comment]
@counter2015 no it does not! i edited my datacenter yaml file and nothing was changed in the pvc / pv. So i edited the pvc manually and the storage was resized ...

**Comment by jsanda** [comment]
The process is actually a bit more involved to do it safely.

First, we need to delete the StatefulSet without deleting the pods. This can be done for example with `kubectl delete --cascade=false`.

Next, make sure that `persistentVolumeReclaimPolicy` on the PV is set to `Retain`. Remove the claim reference. Then delete the PVC.

Now go ahead expand the volume and update the capacity in the PV spec.

Create new PVC that will bind to the PV. The name of the PVC needs to be the same as the name of the old one.

Lastly, recreate the StatefulSet. The StatefulSet controller find the existing PVCs and pods. The StatefulSet will immediately move into the ready state (assuming the pods are ready).

**Comment by counter2015** [comment]
@jsanda Is there any risk to edit the pvc size directly ?

**Comment by jsanda** [comment]
That may work and might be easier than what I prescribed. I would need to do some testing/investigation to be certain.

**Comment by okgolove** [comment]
prometheus-operator (which uses statetulset for prometheus pod as well) offeris [this way](https://prometheus-operator.dev/docs/operator/storage/#resizing-volumes). But this does not work for k8scassandra because of admission webhook:

```admission webhook "vcassandradatacenter.kb.io" denied the request: CassandraDatacenter write rejected, attempted to change storageConfig```

My example:

k8ssandracluster:
```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
spec:
  cassandra:
    serverVersion: "4.0.3"
    serverImage: k8ssandra/cass-management-api:4.0.3
    telemetry:
      prometheus:
        enabled: true
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: gp3-multizone
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
    config:
      jvmOptions:
        heapSize: 512M
    datacenters:
      - metadata:
          name: dc1
        size: 9
        racks:
          - name: r1
            nodeAffinityLabels:
              onairent.live/node-type: cassandra-node
              topology.kubernetes.io/zone: eu-north-1a
          - name: r2
            nodeAffinityLabels:
              onairent.live/node-type: cassandra-node
              topology.kubernetes.io/zone: eu-north-1b
          - name: r3
            nodeAffinityLabels:
              onairent.live/node-type: cassandra-node
              topology.kubernetes.io/zone: eu-north-1c
```

- Change `storage` to 150Gi
- Apply changed manifest
- Patch PVCs
```
for p in $(kubectl get pvc -l cassandra.datastax.com/datacenter=dc1 -o jsonpath='{range .items[*]}{.metadata.name} {end}'); do \
  kubectl patch pvc/${p} --patch '{"spec": {"resources": {"requests": {"storage":"150Gi"}}}}'; \
done
```
- Delete statefulsets
```
kubectl delete statefulset -l cassandra.datastax.com/datacenter=dc1 --cascade=orphan
```

After that no changes are applied to cassandra cluster due to the error mentioned above. Even if I try to resize my cluster I get the error and nothing happens.
