### ISSUE TITLE
K8SSAND-1190 ⁃ How do I make sure the resource has been set up correctly on cassandra ?

### ISSUE THREAD

**Issue by counter2015** [k8ssandra/cass-operator#265]
**What did you do?**

I used following config to create cluster

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
  namespace: cassandra
spec:
  podTemplateSpec:
    spec:
      containers:
        - name: "cassandra"
          image: "k8ssandra/cass-management-api:4.0.1"
          terminationMessagePath: "/dev/other-termination-log"
          terminationMessagePolicy: "File"
  clusterName: transmitter
  serverType: cassandra
  serverVersion: "4.0.1"
  managementApiAuth:
    insecure: {}
  size: 3
  resource:
    requests:
      memory: 12Gi
      cpu: 3000m
    limits:
      memory: 12Gi
      cpu: 3000m
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: gp2-wffc
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
  config:
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
      enable_sasi_indexes: true
    jvm-server-options:
      initial_heap_size: 12G
      max_heap_size: 12G
```

However, in stated cluster, I cant find `spec.containers.resource` field with any settings, it's `resources: {}`, and other containers like `server-config-init` has beed set resource limit . 

When access in container , I found `Xms` and `Xmx` has been set to `12G` by` ps -ef | grep cassandra | grep Xm --color=auto`. But I'm not sure the limit `12Gi` and `cpu 3000m` has been set on pod.

How can I check the config has been set correctly on cassandra ?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1190) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1190
┆priority: Medium
