### ISSUE TITLE
K8SSAND-1269 ⁃ Private registry do not work

### ISSUE THREAD

**Issue by github-vincent-miszczak** [k8ssandra/cass-operator#278]
**What happened?**
I wanted to use a private registry for resources managed by `cass-operator@v1.9.0` (managed by `K8ssandra@v1.4.1`) and while the operator itself was able to be pulled from private registry, it was not the case for the resources it manages.

**Did you expect to see something different?**
Yes, I expected my Cassandra pods to use my private registry as requested.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy `cass-operator` using `k8ssandra` for instance, look at `k8ssandra-cass-operator-manager-config` configmap and look the key 

```
image_config.yaml: |
    apiVersion: config.k8ssandra.io/v1beta1
    kind: ImageConfig
    images:
      system-logger: "k8ssandra/system-logger:v1.9.0"
      config-builder: "datastax/cass-config-builder:1.0.4-ubi7"
    imageRegistry: XXX.dkr.ecr.eu-west-1.amazonaws.com
    imagePullPolicy: Always 
```

Look at your pods/statefulsets managed by `cass-operator` and see that it does not use this registry.

After investigation I found that https://github.com/k8ssandra/cass-operator/blob/master/apis/config/v1beta1/imageconfig_types.go#L38 is the cause. The expected JSON key is `imageRegistryOverride` and the configuration use `imageRegistry`. From examples, the correct key should be `imageRegistry`.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1269) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1269
┆priority: Medium
