### ISSUE TITLE
K8SSAND-1309 ⁃ ImageConfig does not configure Cassandra container

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/cass-operator#290]
**What happened?**

I was attempting to test whether `ImageConfig` or the `CassandraDatacenter`'s `serverImage` took precedence when both were defined, I found that neither actually modified the image used by the cassandra container.

I set `ImageConfig.images.cassandra.[4.0.0.]` to `defined-in-imageconfig/cassandra-ubi:latest`.

I set `CassandraDatacenter.spec.serverImage` to `defined-in-cassdc/cassandra:latest`.

My StatefulSet reports: `Image: k8ssandra/mgmtapi-4_0:latest`.

**Did you expect to see something different?**

Yes, I expected to see either `defined-in-imageconfig` or `defined-in-cassdc` as the image used by the Cassandra container.

**How to reproduce it (as minimally and precisely as possible)**:

## Kustomization
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../config/deployments/cluster

patches:
- target:
    kind: ConfigMap
    name: cass-operator-manager-config
  patch: |
    - op: replace 
      path: /data/image_config.yaml
      value: |
        apiVersion: config.k8ssandra.io/v1beta1
        kind: ImageConfig
        metadata:
          name: image-config
        images:
          system-logger: "my-registry/system-logger-image-test:v0.0.1"
          config-builder: "datastax/cass-config-builder:1.0.4-ubi7"
          cassandra:
            "4.0.0": "defined-in-imageconfig/cassandra-ubi:latest"
          # dse:
          #   "6.8.999": "datastax/dse-server-prototype:latest"
        # imageRegistry: "localhost:5000"
        # imagePullPolicy: Always
        # imagePullSecret:
        #   name: my-secret-pull-registry
        defaults:
          # Note, postfix is ignored if repository is not set
          cassandra:
            repository: "k8ssandra/cass-management-api"
          dse:
            repository: "datastax/dse-server"
            suffix: "-ubi7"
```

## Cassandra Datacenter
```
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
  namespace: cass-operator
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: 4.0.0
  serverImage: defined-in-cassdc/cassandra:latest
  managementApiAuth:
    insecure: {}
  size: 1
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1309) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1309
┆priority: Medium
