### ISSUE TITLE
K8SSAND-1461 ⁃ configBuilderResources does not have impact on server-config-init

### ISSUE THREAD

**Issue by kevin85421** [k8ssandra/cass-operator#321]
# What did you do?
As mentioned in https://github.com/k8ssandra/cass-operator/issues/150, `configBuilderResources`, the resource configuration of `server-config-init` can be set by `configBuilderResources`.

```sh
# Step1: Install cert-manager
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.yaml

# Step2: Install operator
kubectl apply --force-conflicts --server-side -k 'github.com/k8ssandra/cass-operator/config/deployments/cluster?ref=v1.10.3'

# Step3: Apply custom resource
kubectl apply -f cr1_spec.yaml

# Step4: Check CR for the "Config Builder Resources" field => The field is empty
kubectl describe cassandradatacenters.cassandra.datastax.com cassandra-datacenter

# Config Builder Resources:

# Step5: Check statefulset for the resource request config of server-config-init => Default value (correct)
kubectl describe statefulsets.apps cluster1-cassandra-datacenter-default-sts

 #  server-config-init:
 #   Image:      datastax/cass-config-builder:1.0.4-ubi7
 #   Port:       <none>
 #   Host Port:  <none>
 #   Limits:
 #     cpu:     1
 #     memory:  256M
 #   Requests:
 #     cpu:     1
 #     memory:  256M

# Step6: Update cassandra-datacenter
kubectl apply -f cr2_spec.yaml

# Step7: Check CR for the "Config Builder Resources" field => The field is the same as cr2_spec.yaml
kubectl describe cassandradatacenters.cassandra.datastax.com cassandra-datacenter

#  Config Builder Resources:
#    Requests:
#      Cpu:     512m
#      Memory:  100m

# Step8: Check statefulset for the resource request config of server-config-init => Not the same as cr2_spec.yaml
kubectl describe statefulsets.apps cluster1-cassandra-datacenter-default-sts

 #  server-config-init:
 #   Image:      datastax/cass-config-builder:1.0.4-ubi7
 #   Port:       <none>
 #   Host Port:  <none>
 #   Limits:
 #     cpu:     1
 #     memory:  256M
 #   Requests:
 #     cpu:     1
 #     memory:  256M



```

* `cr1_spec.yaml`

```yaml
 apiVersion: cassandra.datastax.com/v1beta1
 kind: CassandraDatacenter
 metadata:
   name: cassandra-datacenter
 spec:
   clusterName: cluster1
   config:
     cassandra-yaml:
       authenticator: org.apache.cassandra.auth.PasswordAuthenticator
       authorizer: org.apache.cassandra.auth.CassandraAuthorizer
       role_manager: org.apache.cassandra.auth.CassandraRoleManager
     jvm-options:
       initial_heap_size: 800M
       max_heap_size: 800M
   managementApiAuth:
     insecure: {}
   serverType: cassandra
   serverVersion: 3.11.7
   size: 1
   storageConfig:
     cassandraDataVolumeClaimSpec:
       accessModes:
       - ReadWriteOnce
       resources:
         requests:
           storage: 3Gi
       storageClassName: server-storage
```

* `cr2_spec.yaml`

```yaml
 apiVersion: cassandra.datastax.com/v1beta1
 kind: CassandraDatacenter
 metadata:
   name: cassandra-datacenter
 spec:
   clusterName: cluster1
   config:
     cassandra-yaml:
       authenticator: org.apache.cassandra.auth.PasswordAuthenticator
       authorizer: org.apache.cassandra.auth.CassandraAuthorizer
       role_manager: org.apache.cassandra.auth.CassandraRoleManager
     jvm-options:
       initial_heap_size: 800M
       max_heap_size: 800M
   configBuilderResources:
     requests:
       memory: 100m
       cpu: 512m
   managementApiAuth:
     insecure: {}
   serverType: cassandra
   serverVersion: 3.11.7
   size: 1
   storageConfig:
     cassandraDataVolumeClaimSpec:
       accessModes:
       - ReadWriteOnce
       resources:
         requests:
           storage: 3Gi
       storageClassName: server-storage
```

# Did you expect to see some different?
In Step8, I expected that `server-config-init` should have the same resource request configurations as `cr2_spec.yaml`.

# Environment
* Cass Operator version:

    `docker.io/k8ssandra/cass-operator:v1.10.3`
    
    * Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

```
minikube start --vm-driver=docker --cpus 4 --memory 4096 --kubernetes-version v1.21.0
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1461) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1461
┆priority: Medium
