### ISSUE TITLE
K8SSAND-1552 ⁃ Cluster names with spaces will prevent DC deployment

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/cass-operator#345]
**What happened?**
When deploying a DC with spaces in the cluster name, the operator fails creating all resources due to invalid labels on some of them.
Label values cannot contain special characters nor spaces.

**Did you expect to see something different?**
Spaces in cluster names should be handled automatically and sanitized everywhere it's needed.

**How to reproduce it (as minimally and precisely as possible)**:
Create a cassdc definition with a space in the `ClusterName`.

* Cass Operator version:

    `v1.11.0`
    
    * Manifest

```
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc2
spec:
  clusterName: cluster 2
  serverType: cassandra
  serverVersion: "4.0.0"
  managementApiAuth:
    insecure: {}
  size: 1
  storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 250Mi
  racks:
    - name: r1
  config:
    jvm-server-options:
      initial_heap_size: "512m"
      max_heap_size: "512m"
    cassandra-yaml:
      num_tokens: 16
```

* Cass Operator Logs:

```
1.6548742060704772e+09	ERROR	controllers.CassandraDatacenter.cassandradatacenter_controller.controller.cassandradatacenter-controller	Could not create headless service	{"reconciler group": "cassandra.datastax.com", "reconciler kind": "CassandraDatacenter", "name": "dc1", "namespace": "k8ssandra-operator", "namespace": "k8ssandra-operator", "datacenterName": "dc1", "clusterName": "Weird Cluster Name", "error": "Service \"weirdclustername-dc1-service\" is invalid: [metadata.labels: Invalid value: \"Weird Cluster Name\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), metadata.labels: Invalid value: \"cassandra-Weird Cluster Name\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), spec.selector: Invalid value: \"Weird Cluster Name\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]"}
github.com/k8ssandra/cass-operator/pkg/reconciliation.(*ReconciliationContext).CheckHeadlessServices
	/workspace/pkg/reconciliation/reconcile_services.go:130
github.com/k8ssandra/cass-operator/pkg/reconciliation.(*ReconciliationContext).CalculateReconciliationActions
	/workspace/pkg/reconciliation/handler.go:142
github.com/k8ssandra/cass-operator/controllers/cassandra.(*CassandraDatacenterReconciler).Reconcile
	/workspace/controllers/cassandra/cassandradatacenter_controller.go:143
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227
```

**Anything else we need to know?**:

This is blocking work on https://github.com/k8ssandra/k8ssandra-operator/issues/496

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1552) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1552
┆priority: Medium
