### ISSUE TITLE
K8SSAND-1760 ⁃ Setup task failed with error

### ISSUE THREAD

**Issue by shengzhizhou** [k8ssandra/cass-operator#401]
Hi, I installed cass-operator 1.10.4/serverVersion 4.0.3 with 1 dc and 3 nodes, two of the nodes work fine and I can login to it, only one of the nodes shows up but I can't login and shows Connection refused. 
Here's the log of server-system-logger: 

```
...
java.lang.RuntimeException: Failed to rename /var/lib/cassandra/data/system_auth/roles-5bc52802de2535edaeab188eecebb090/nb-1-big-Statistics.db.tmp to /var/lib/cassandra/data/system_auth/roles-5bc52802de2535edaeab188eecebb090/nb-1-big-Statistics.db
...
Caused by: java.nio.file.AccessDeniedException: /var/lib/cassandra/data/system_auth/roles-5bc52802de2535edaeab188eecebb090/nb-1-big-Statistics.db.tmp -> /var/lib/cassandra/data/system_auth/roles-5bc52802de2535edaeab188eecebb090/nb-1-big-Statistics.db
...
INFO [OptionalTasks:1] 2022-08-31 18:50:44,497 CassandraRoleManager.java:370 - Setup task failed with error, rescheduling
WARN [OptionalTasks:1] 2022-08-31 18:50:54,499 CassandraRoleManagerInterceptor.java:75 - CassandraRoleManager skipped default role setup: some nodes were not ready
```

I wonder why only one nodes has this issue? Shouldn't all 3 nodes apply same setting? Anyone has idea how to fix it?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1760) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1760
┆priority: Medium

**Comment by burmanm** [comment]
Did you copy (or mount) some existing files there? Why are the rights incorrect?

**Comment by shengzhizhou** [comment]
no, I didn't put or mount files. I only run cqlsh in it.

**Comment by shengzhizhou** [comment]
Hi, any suggestion on this issue? Thanks.

**Comment by burmanm** [comment]
It's most likely a Cassandra error more than cass-operator. You could try replacing that node. Set the correct node replacement, remove the PVCs and delete the pod.

**Comment by shengzhizhou** [comment]
Hi, is there any documentation about this process? Thanks. 
By replace node, do you mean recreating a new kubernetes node and replace it, or just delete the existing Cassandra pods and recreating pods?

**Comment by burmanm** [comment]
Hi,

No. I mean in the CassandraDatacenter, add to `.spec.replaceNodes` the podName you wish to replace. Then delete the PVCs of that pod (it will block, but don't worry - ctrl+c is fine after waiting few seconds) and then delete the pod. cass-operator should recreate everything necessary. Assuming it joined the ring, if it never did, then just deleting the PVC + pod should be enough.

**Comment by shengzhizhou** [comment]
Hi, for PVC you mean the Persistent Volume Claim, right? or I need to delete Persistent Volume too?

**Comment by burmanm** [comment]
Safest way of course is to delete both to ensure there's for sure no old data.

**Comment by shengzhizhou** [comment]
okay, thanks. Another question: Do I need to remove .spec.replaceNodes after it recreated?
Actually I delete everything and redeploy cass-operator and DataCenter more than once, each time it shows different error. But I will try this replaceNodes and see.

**Comment by burmanm** [comment]
Reinstalling cass-operator won't make a difference, since the persistence is handled by the Kubernetes StS controller.

**Comment by shengzhizhou** [comment]
Sadly replaceNodes doesn't solve issue, the logs still show exactly same error message:  
``` java.lang.RuntimeException: Failed to rename /var/lib/cassandra/data/system_auth/roles-5bc52802de2535edaeab188eecebb090/nb-1-big-Statistics.db.tmp to /var/lib/cassandra/data/system_auth/roles-5bc52802de2535edaeab188eecebb090/nb-1-big-Statistics.db ```

**Comment by burmanm** [comment]
Did you delete the PV (if the PVC has retain)? To me that looks like the old data.

**Comment by shengzhizhou** [comment]
yes, I delete old PV

**Comment by shengzhizhou** [comment]
Hi, I just redeployed again, PV/PVC are deleted, mount folder deleted, still only one of the pods shows permission error.

**Comment by shengzhizhou** [comment]
I tried with 2 nodes, just for testing, both works fine. but when I tried with 3 nodes it shows one of the nodes has issue. Is there any config I'm missing here : 
```
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
  namespace: acd
spec:
  nodeSelector:
    kubernetes.io/os: linux
  clusterName: cluster1
  serverType: cassandra
  serverVersion:"4.0.3"
  managementApiAuth:
    insecure: {}
  size: 3
  storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: fs-cassandra
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  dockerImageRunsAsCassandra: true
  resources:
    requests:
      memory: 2Gi
      cpu: 1000m
  racks:
    - name: rack1
  config:
    cassandra-env-sh:
      additional-jvm-opts:
        - -Dcassandra.system_distributed_replication_dc_names=dc1
        - -Dcassandra.system_distributed_replication_per_dc=3
        - -Dcom.sun.management.jmxremote.authenticate=true 
    jvm-server-options:
      initial_heap_size: "1G"
      max_heap_size: "1G"
    cassandra-yaml:
      num_tokens: 16
      authenticator: PasswordAuthenticator
      authorizer: CassandraAuthorizer
      role_manager: CassandraRoleManager 
```
