### ISSUE TITLE
K8SSAND-1764 ⁃ Recreating all cassdc pods triggers "The seed provider lists no seeds" error

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/cass-operator#402]
**What happened?**
When deleting all pods from a cassdc instance (or performing a change on a cassdc with a single replica in the statefulset), upon pods restart, none get labeled as seed.
This then puts the first node in a boot loop as it doesn't get promoted as seed.
Fixing this situation requires multiple restarts of individual pods until cass-operator promotes one as seed.

This error was first reported here: https://github.com/k8ssandra/k8ssandra-operator/issues/567

**Did you expect to see something different?**
The first starting nodes should be labeled as seeds despite pods being ungracefully deleted.

**How to reproduce it (as minimally and precisely as possible)**:

* Create a cassdc with any number of replicas
* Delete all pods some time after startup
* First pod with the "Starting" label will get into a boot loop with the following errors:

```
WARN  [main] 2022-09-06 15:40:14,972 K8SeedProvider4x.java:58 - Seed provider couldn't lookup host testing-new-seed-service
WARN  [main] 2022-09-06 15:40:15,070 K8SeedProvider4x.java:58 - Seed provider couldn't lookup host testing-new-dc1-additional-seed-service
ERROR [main] 2022-09-06 15:40:15,074 CassandraDaemon.java:911 - Exception encountered during startup: The seed provider lists no seeds.
```

* Cass Operator version:

    `v1.12.0`
    
    * Manifests:

```
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
  namespace: k8ssandra-operator
spec:
  additionalServiceConfig:
    additionalSeedService: {}
    allpodsService: {}
    dcService: {}
    nodePortService: {}
    seedService: {}
  clusterName: testing-new
  config:
    cassandra-env-sh:
      additional-jvm-opts:
        - '-Dcassandra.system_distributed_replication=dc1:3'
        - '-Dcom.sun.management.jmxremote.authenticate=true'
    cassandra-yaml:
      authenticator: PasswordAuthenticator
      authorizer: CassandraAuthorizer
      num_tokens: 16
      role_manager: CassandraRoleManager
    jvm-server-options:
      initial_heap_size: 512000000
      max_heap_size: 512000000
    jvm11-server-options:
      garbage_collector: G1GC
  configBuilderResources: {}
  managementApiAuth: {}
  networking: {}
  podTemplateSpec:
    metadata: {}
    spec:
      containers:
        - env:
            - name: METRIC_FILTERS
              value: >-
                deny:org.apache.cassandra.metrics.Table
                deny:org.apache.cassandra.metrics.table
                allow:org.apache.cassandra.metrics.table.live_ss_table_count
                allow:org.apache.cassandra.metrics.Table.LiveSSTableCount
                allow:org.apache.cassandra.metrics.table.live_disk_space_used
                allow:org.apache.cassandra.metrics.table.LiveDiskSpaceUsed
                allow:org.apache.cassandra.metrics.Table.Pending
                allow:org.apache.cassandra.metrics.Table.Memtable
                allow:org.apache.cassandra.metrics.Table.Compaction
                allow:org.apache.cassandra.metrics.table.read
                allow:org.apache.cassandra.metrics.table.write
                allow:org.apache.cassandra.metrics.table.range
                allow:org.apache.cassandra.metrics.table.coordinator
                allow:org.apache.cassandra.metrics.table.dropped_mutations
            - name: MANAGEMENT_API_HEAP_SIZE
              value: '67108864'
          name: cassandra
          resources: {}
      initContainers:
        - args:
            - /bin/sh
            - '-c'
            - >-
              echo "$SUPERUSER_JMX_USERNAME $SUPERUSER_JMX_PASSWORD" >>
              /config/jmxremote.password
          env:
            - name: SUPERUSER_JMX_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: testing-new-superuser
            - name: SUPERUSER_JMX_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: testing-new-superuser
          image: docker.io/library/busybox:1.34.1
          imagePullPolicy: IfNotPresent
          name: jmx-credentials
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: server-config
  resources: {}
  serverImage: k8ssandra/cass-management-api:4.0.3
  serverType: cassandra
  serverVersion: 4.0.3
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: standard
  superuserSecretName: testing-new-superuser
  systemLoggerResources: {}

```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1764) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1764
┆priority: Medium
