### ISSUE TITLE
K8SSAND-1837 ⁃ Succeeded field in CassandraTask status does not get updated for restart task

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/cass-operator#431]
**What happened?**
I created a CassandraTask to perform a rolling restart on a 3 node DC. The `.status.succeeded` field of the CassandraTask was never updated. I assume the same problem exists for `.status.failed` but the restarts were all successful so I can't say for certain.

**Did you expect to see something different?**
`.status.succeeded` should get updated as per the API docs. I do see this behavior for other CasssandraTask types.

**How to reproduce it (as minimally and precisely as possible)**:
Create a 3-node CassandraDatacenter in a namespace named `test`:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: test
  serverType: cassandra
  serverVersion: 4.0.3
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: standard
```

Once the CassandraDatacenter is ready create a CassandraTask:

```yaml
apiVersion: control.k8ssandra.io/v1alpha1
kind: CassandraTask
metadata:
  name: restart-dc
spec:
  datacenter:
    name: dc1
    namespace: test
  jobs:
    - name: restart-dc1
      command: restart
```

**Environment**

* Cass Operator version:

    `v1.13.0`
    
    

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1837) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1837
┆priority: Medium
