### ISSUE TITLE
Extract task execution attributes into an inlined struct

### ISSUE THREAD

**Issue by olim7t** [k8ssandra/cass-operator#457]
**What is missing?**

In k8ssandra/k8ssandra-operator#739 we will introduce a `K8ssandraTask` resource, that triggers a `CassandraTask` for each datacenter in the cluster:
```yaml
apiVersion: control.k8ssandra.io/v1alpha1
kind: K8ssandraClusterTask
metadata:
  name: upgradesstables
spec:
  cluster:
    name: cluster1
  datacenters:
    - dc3
    - dc1
  spec:
    jobs:
      - name: upgradesstables-dc1
        command: upgradesstables
```
The `spec` part is almost identical to `CassandraTask`, except that it won't have a `datacenter` field. It would be nice to have a struct that we can reuse, instead of duplicating all the required fields.

**Why do we need it?**

Code reuse, maintainability.

**Environment**

Any.

* Cass Operator version: > 1.13.1

**Anything else we need to know?**:
