### ISSUE TITLE
priorityClassName support

### ISSUE THREAD

**Issue by Mokto** [k8ssandra/cass-operator#550]
### What is missing?

priorityClassName support is surprisingly missing from the CRD.

Maybe I'm missing something but it doesn't seem possible right now to set this value.

### Why is this needed?

It's a standard (and highly used) field in Kubernetes.

**Comment by burmanm** [comment]
You can already set this value under podTemplateSpec/spec/priorityClassName. For example:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc2
spec:
  clusterName: cluster2
  serverType: cassandra
  serverVersion: "4.0.7"
  managementApiAuth:
    insecure: {}
  size: 1
  podTemplateSpec:
    spec:
      containers:
        - name: "cassandra"
      priorityClassName: my-priority
  storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  racks:
    - name: r1
  config:
    jvm-options:
      initial_heap_size: "512m"
      max_heap_size: "512m"
```

**Comment by Mokto** [comment]
Thanks ! I'll try it soon

**Comment by JBOClara** [comment]
I'am not able to do this with K8ssandraCluster object: 

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  annotations:
    k8ssandra.io/initial-system-replication: '{"us-east":3}'
  name: test
  namespace: k8ssandra-operator
spec:
  auth: true
  cassandra:
  ...
```

As a workaround, I've been using a Gatekeeper Mutator

```yaml
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: change-priority-class
spec:
  applyTo:
    - groups: ["apps"]
      kinds: ["StatefulSet"]
      versions: ["v1"]
  match:
    source: "All"
    scope: Namespaced
    kinds:
    - apiGroups: ["apps"]
      kinds: ["StatefulSet"]
    namespaces: ["k8ssandra-operator"]
    labelSelector:
      matchLabels:
        app.kubernetes.io/created-by: cass-operator
  location: "spec.template.spec.priorityClassName"
  parameters:
    assign:
      value: system-cluster-critical
```
