### ISSUE TITLE
Do we support use storage size equal or greater than 1024Gi?

### ISSUE THREAD

**Issue by sherryhao** [k8ssandra/cass-operator#596]
### What happened?
Hi experts,

We are continously seeing this kind of error with storage size set to 1024Gi when deploying CassandraDatacenter.

"admission webhook "vcassandradatacenter.kb.io" denied the request: CassandraDatacenter write rejected, attempted to change storageConfig"

![1699876353185](https://github.com/k8ssandra/cass-operator/assets/93966987/7636ff88-6f33-4d1a-b3b9-5cb2e0fc2565)

![image](https://github.com/k8ssandra/cass-operator/assets/93966987/e7f99691-f087-43c7-90f1-c38535d5a2fb)

  storageConfig:
    cassandraDataVolumeClaimSpec:

# reclaimPolicy: Retain
```
  storageClassName: managed-csi-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1024Gi
```

But, once we reduced the size to a smaller one, say 500Gi, then services come up as expected with all required pvc created successfully.

Would you kindly suggest if there is any limation to the storage size?

Install command: helm install cass-operator k8ssandra/cass-operator -n cass-operator--version=0.40.0

Cluster is running on AKS+managed-csi-premium

### What did you expect to happen?
Support storage size equal or greater than 1024Gi.

### How can we reproduce it (as minimally and precisely as possible)?
Cluster running on AKS and deploy CassandraDatacenter with storage size 1024Gi.

sample configuration: 
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: cassandra
  namespace: cass-operator
spec:
  clusterName: xxxx
  serverType: cassandra
  serverVersion: "4.0.7"
  managementApiAuth:
    insecure: {}
  size: 3
  allowMultipleNodesPerWorker: true
  resources:
    requests:
      cpu: 500m
      memory: 24Gi
    limits:
      cpu: 2
      memory: 24Gi
  storageConfig:
    cassandraDataVolumeClaimSpec:

# reclaimPolicy: Retain
```
  storageClassName: managed-csi-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
```

### cass-operator version
0.40.0

### Kubernetes version
v1.25

### Method of installation
helm

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/CASS-15) by [Unito](https://www.unito.io)
┆Issue Number: CASS-15
