### ISSUE TITLE
Allow volume addition

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/cass-operator#602]
### What is missing?
We currently don't have an automated way of expanding the storage capacity of Cassandra pods.
This can lead to tricky situations in production where storage is close to being full and cluster expansion would take too long to mitigate the issue.

In some cases, volume expansion will be possible if the storage class allows it, but there are cases where it will be faster to attach an additional volume to the pods and configure Cassandra to use it as additional data directory.

Scenario should be automated in cass-operator and handle manipulating the statefulsets to achieve this, removing the odds of misconfiguration and data loss.

### Why is this needed?
It is common to run out of disk space with Cassandra under circumstances where either capacity planning hasn't been thought in advance or compaction and tombstone reclaiming isn't performing as expected.
We need to ensure that there's an easy path out of such critical situations in production.

```
### Requirements
- [ ] #609 Is implemented to allow metadata which volumes are used for data volume expansion
- [ ] Volumes are allowed to be modified in the StatefulSet
```

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/CASS-14) by [Unito](https://www.unito.io)
┆Issue Number: CASS-14

**Comment by burmanm** [comment]
This should be split to two different tickets, as adding volumes is a very separate implementation detail. It's also related to #609 since currently additional volumes do not have indication what they're used for.

**Comment by artsiom-bukhautsou** [comment]
This issue has been investigated, and there is no safe way to fix it on our end. The root cause lies in the Kubernetes StatefulSet controller logic: it treats PVCs as immutable, fails to update them (see [stateful_set_control.go#L501](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/statefulset/stateful_set_control.go#L501)), and does not recreate the affected Pods.

Additionally, this condition is not reflected in the StatefulSet status, which means we cannot reliably detect, track, or automatically mitigate the issue.

Therefore, after changing additional volumes, we recommend doing it via CassandraTask .
Example:
```yaml
apiVersion: control.k8ssandra.io/v1alpha1
kind: CassandraTask
metadata:
  name: rolling-restart
spec:
  datacenter:
    name: dc2 # name of the CassandraDatacenter
    namespace: cass-operator # namespace where the DC is deployed
  jobs:
    - name: restart-run
      command: restart
```

Triggering a rolling restart forces the Pods to be recreated. During Pod recreation, the corresponding PVCs and PVs are created with the updated volume configuration, which resolves the issue.
