### ISSUE TITLE
Certified operator bundle creation missing annotations

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/cass-operator#679]
### What happened?

The initial build in RedHat's CI pipeline failed when using release-certified-operators.sh

The CSV file should have the following annotations added to it (current packaging / functionality):

```yaml
    features.operators.openshift.io/disconnected: "false"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
```

### What did you expect to happen?

It should work.

### How can we reproduce it (as minimally and precisely as possible)?

https://github.com/redhat-openshift-ecosystem/certified-operators/pull/4150

### cass-operator version

1.21.1

### Kubernetes version

1.30

### Method of installation

OLM
