### ISSUE TITLE
Cass-operator is unable to delete Users in Cassandra

### ISSUE THREAD

**Issue by kos-team** [k8ssandra/cass-operator#694]
### What happened?
We want to delete a user that we previously created through the `spec.users` property in the CRD. However, by removing the user entry from the `spec.users` list, we found that the user still exist in the Cassandra system.

### What did you expect to happen?
There are two right behaviors in this case, depending how much feature this operator wants to support:

1. Make the operator to manage the list of users that it creates. When a user is removed from the CR, it should be deleted from the Cassandra cluster.
1. Make the `spec.users` an immutable field. This can be done easily with the `x-kubernetes-validation` CRD feature.

### How can we reproduce it (as minimally and precisely as possible)?
1. Deploy the cass-operator
1. Create two secrets for the Cassandra users:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-secret-2
type: Opaque
data:
  username: YWRtaW4y
  password: cGFzc3dvcmQ=
```

1. Deploy CassandraDB with the following CR yaml

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: test-cluster
spec:
  clusterName: development
  serverType: cassandra
  serverVersion: "4.1.2"
  managementApiAuth:
    insecure: {}
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  racks:
    - name: rack1
  config:
    jvm-server-options:
      initial_heap_size: "1G"
      max_heap_size: "1G"
    cassandra-yaml:
      num_tokens: 16
      authenticator: PasswordAuthenticator
      authorizer: CassandraAuthorizer
      role_manager: CassandraRoleManager
  users:
  - secretName: demo-secret
    superuser: true
  - secretName: demo-secret-2
    superuser: false
```

1. Delete the `demo-secret-2` user from the `spec.users`:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: test-cluster
spec:
  clusterName: development
  serverType: cassandra
  serverVersion: "4.1.2"
  managementApiAuth:
    insecure: {}
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  racks:
    - name: rack1
  config:
    jvm-server-options:
      initial_heap_size: "1G"
      max_heap_size: "1G"
    cassandra-yaml:
      num_tokens: 16
      authenticator: PasswordAuthenticator
      authorizer: CassandraAuthorizer
      role_manager: CassandraRoleManager
  users:
  - secretName: demo-secret
    superuser: true
```

1. Observe the list of users by running `LIST USERS` in cqlsh:

```
 name                  | super  | datacenters
-----------------------+--------+-------------
 development-superuser |  True  |         ALL
 admin                 |  True  |         ALL
 admin-2               |  False |        ALL
```

### cass-operator version
1.22.0

### Kubernetes version
1.28.0

### Method of installation
Helm

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/CASS-3) by [Unito](https://www.unito.io)
┆Issue Number: CASS-3
