### ISSUE TITLE
Starting process should ignore Pending state pods and start the next one in the rack

### ISSUE THREAD

**Issue by kos-team** [k8ssandra/cass-operator#696]
### What happened?
We are trying to resume a stopped Cassandra cluster. The cluster may not have the enough resource to schedule all the Pods, and we found that in some cases the seed nodes in racks may be in `pending` state while other nodes are scheduled but cannot start correctly because of the lack of seed node.

### What did you expect to happen?
The operator should prioritize seed nodes when creating the Cassandra pods. If the seed node is not scheduled, the entire rack is defunct.

### How can we reproduce it (as minimally and precisely as possible)?
1. Deploy the cass-operator
1. Deploy CassandraDB with the following CR yaml in a resource limited cluster. For example, a Kind cluster with only 4 nodes.

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: test-cluster
spec:
  clusterName: development
  serverType: cassandra
  serverVersion: "4.1.2"
  managementApiAuth:
    insecure: {}
  size: 6
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  racks:
    - name: rack1
  config:
    jvm-server-options:
      initial_heap_size: "1G"
      max_heap_size: "1G"
    cassandra-yaml:
      num_tokens: 16
      authenticator: PasswordAuthenticator
      authorizer: CassandraAuthorizer
      role_manager: CassandraRoleManager
```

1. In some cases the seed node of the rack is not scheduled while other nodes are being scheduled.

### cass-operator version
1.22.0

### Kubernetes version
1.29.1

### Method of installation
Helm

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/CASS-1) by [Unito](https://www.unito.io)
┆Issue Number: CASS-1
