### ISSUE TITLE
I want to add a new directory to the data directory, but I found that STS does not automatically create PVC. What do I need to do

### ISSUE THREAD

**Issue by xiongmozhou** [k8ssandra/cass-operator#732]
conf.yaml
```yaml
  cassandra:
    serverVersion: "4.0.1"
    datacenters:
      - metadata:
          name: dc1
        size: 3
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: open-local-lvm
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
          additionalVolumes:
            - name: data01
              mountPath: /opt/tmp01
              pvcSpec:
                storageClassName: open-local-lvm
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
            - name: data02
              mountPath: /opt/tmp02
              pvcSpec:
                storageClassName: open-local-lvm
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 2Gi
            - name: data03
              mountPath: /opt/tmp03
              pvcSpec:
                storageClassName: open-local-lvm
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 3Gi
        config:
          jvmOptions:
            heapSize: 512M
          cassandraYaml:
            cdc_enabled: true
            counter_write_request_timeout_in_ms: 10000
            data_file_directories:
              - /opt/tmp01
              - /opt/tmp02
              - /opt/tmp03

```

The storage configuration for data03 was added later. After I applied it again, I found that data03 PVC was not created and the pod restart failed

log:

  Warning  FailedCreate      5m20s (x17 over 10m)  statefulset-controller  create Pod demo-dc1-default-sts-2 in StatefulSet demo-dc1-default-sts failed error: Pod "demo-dc1-default-sts-2" is invalid: [spec.containers[0].volumeMounts[2].name: Not found: "data03", spec.containers[2].volumeMounts[2].name: Not found: "data03"]

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/CASS-80) by [Unito](https://www.unito.io)
┆Issue Number: CASS-80
