### ISSUE TITLE
NodePort configuration does not work as expected

### ISSUE THREAD

**Issue by phillowAT** [k8ssandra/cass-operator#735]
### What happened?

When trying to configure a Cassandra Cluster with nodeport for cqlsh, I get an error in cass-operator logs like:
spec.ports[0].nodePort: Invalid value: 7000

### What did you expect to happen?

service gets properly assigned with highport as configured in cassandra_cluster.yaml

### How can we reproduce it (as minimally and precisely as possible)?

apply cassdc yaml as below

### cass-operator version

1.19.2

### Kubernetes version

1.26.13

### Method of installation

Helm

### Anything else we need to know?

###Env:
Cassandra clusters are installed on OCP, with multiple instances running successfully without nodeport cfg.

### cass-operator logs:
2024-11-19T16:50:15.870Z        INFO    controllers.CassandraDatacenter Reconcile loop completed        {"cassandradatacenter": "test/dc1", "requestNamespace": "test", "requestName": "dc1", "loopID": "8b3ee225-2474-449f-b85d-e418052023a6", "duration": 0.012072161}
2024-11-19T16:50:15.870Z        ERROR   Reconciler error        {"controller": "cassandradatacenter_controller", "controllerGroup": "cassandra.datastax.com", "controllerKind": "CassandraDatacenter", "CassandraDatacenter": {"name":"dc1","namespace":"test"}, "namespace": "test", "name": "dc1", "reconcileID": "19fe6de2-0d17-4ddc-bb77-72312c33b6e8", "error": "Service \"cluster1-dc1-node-port-service\" is invalid: spec.ports[0].nodePort: Invalid value: 7000: provided port is not in the valid range. The range of valid ports is 30000-32767"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235

### cassdc yaml:
```
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
  namespace: test
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: "4.1.2"
  managementApiAuth:
   insecure: {}
  networking:
    nodePort:
      cql: 30001
      broadcast: 30002
  size: 3
  storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: storage-rwo-ext4-retain
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  podTemplateSpec:
    spec:
      containers:
        - name: "cassandra"
      securityContext: {}
  resources:
    requests:
      memory: 6Gi
      cpu: 500m
    limits:
      memory: 8Gi
      cpu: 800m
```

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/CASS-81) by [Unito](https://www.unito.io)
┆Issue Number: CASS-81

**Comment by burmanm** [comment]
Hey, this restriction is not in cass-operator, but your OCP environment. By default, Kubernetes distributions restrict the nodePorts to be in the range of 30000-32767.

You need to modify your OCP environment to allow for different range.

**Comment by phillowAT** [comment]
Hi burmann,

Thanks for your quick response, really appreciated! 👍🏻 

I am not sure what to look for, but i can create a service in the same namespace with nodeport manually without issues:
```
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 30036
      name: http
  selector:
    name: MySQL
```
    
<img width="720" alt="image" src="https://github.com/user-attachments/assets/9c9a274f-8371-4f88-a907-54c5c759a7d2">

I am not sure where is the difference whether I create a service manually or the operator does (familiar with k8s, not so much with OCP; nor the platform owner)

**Comment by burmanm** [comment]
Your nodePort is in that example the 30036. So that's an allowed value. Try with nodePort: 7000 and see what it says. The other issue could be that as a user when manually creating something, you are logged in as a user with more rights than what the operator has.

**Comment by phillowAT** [comment]
I tested now with:
```
  networking:
      nodePort:
        cql: 7001
        broadcast: 7002
```
and still get:
`2024-11-22T12:31:53.943Z        DEBUG   events  Service "cluster1-dc1-node-port-service" is invalid: spec.ports[0].nodePort: Invalid value: 7000: provided port is not in the valid range. The range of valid ports is 30000-32767      {"type": "Warning", "object": {"kind":"CassandraDatacenter","namespace":"test","name":"dc1","uid":"0d32a203-d105-4579-860e-69b7708cfe12","apiVersion":"cassandra.datastax.com/v1beta1","resourceVersion":"188771403"}, "reason": "ReconcileFailed"}`

I also checked the serviceaccount: cass-operator which has no indication of any limitation in nodeport service, and went through the helmchart of the operator to see if we did missconfigured anything, without luck.
I took the Cassdc.yaml config straight out of your nodeport testcase/the docs for nodeport.

In general it does sound fishy that it always mocks around port 7000, which is the internode com port; and I do not see any reason why I should get back an error from OCP for port 7000 if I am intending to use nodeport above 30k

**Comment by phillowAT** [comment]
Hi burmann,

to not stall the issue (because we´re still suffering):
are your testcases for nodeport running successfully?

I tested now also on a local (dev-)cluster with the same outcome/error.

Thanks for your efforts!

**Comment by burmanm** [comment]
There's two things here, so the 7000 port not being allowed is not cass-operator's fault, but what you wanted was to change those ports (like the MySQL one). I'm not sure how you came up with the configuration however (I'm guessing here the structure as your original comment has missed all the indentations), we don't seem to have a fields networking.nodePort.cql / broadcast. Only native, nativeSSL, internode, internodeSSL fields. 

So if I set this in the YAML:

```yaml
  networking:
    nodePort:
      internode: 30036
      native: 30046
```

What I get is this:

```
➜  cass-operator git:(master) ✗ kubectl get service/cluster2-dc2-node-port-service
NAME                             TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)                           AGE
cluster2-dc2-node-port-service   NodePort   10.96.194.168   <none>        30036:30036/TCP,30046:30046/TCP   14s
➜  cass-operator git:(master) ✗
```

Which seems to be the correct behavior?

**Comment by phillowAT** [comment]
Hi burmann,

thanks for your quick response.
Sorry for the indentation issue, I used the cfg from: [datastax docs](https://docs.datastax.com/en/cassandra-operator/managing/provisioning.html#configure-a-nodeport-service)

Your example does give a good hint, while it seems I stuck on the wrong docs :)
So, I should be lucky with a cfg of "spec.networking.nodePort.native" only (bcs that is what I ultimately seek for), without defining any other of the ports then?
Intention is to get default port for cql on nodeport, while all internode and other internal ports are still handled in cluster network.

I will try to get a testrun done the next hrs and if successful, close the issue here.

**Comment by phillowAT** [comment]
hi again,

i tested now with value
```
  networking:
    nodePort:
      native: 30046
```
and get an error again:

### operator logs:
2024-11-29T11:35:04.073Z        INFO    Service "cluster1-dc1-node-port-service" is invalid: spec.ports[0].nodePort: Invalid value: 7000: provided port is not in the valid range. The range of valid ports is 30000-32767   {"controller": "cassandradatacenter_controller", "controllerGroup": "cassandra.datastax.com", "controllerKind": "CassandraDatacenter", "CassandraDatacenter": {"name":"dc1","namespace":"test"}, "namespace": "test", "name": "dc1", "reconcileID": "1e084c00-439c-440c-855d-3b7b83e187d2", "reason": "ReconcileFailed", "eventType": "Warning"}
2024-11-29T11:35:04.073Z        INFO    controllers.CassandraDatacenter Reconcile loop completed        {"cassandradatacenter": "test/dc1", "requestNamespace": "test", "requestName": "dc1", "loopID": "cbaa8b77-11b6-41d9-b36c-45f0fa79f7d4", "duration": 0.013830524}
2024-11-29T11:35:04.073Z        ERROR   Reconciler error        {"controller": "cassandradatacenter_controller", "controllerGroup": "cassandra.datastax.com", "controllerKind": "CassandraDatacenter", "CassandraDatacenter": {"name":"dc1","namespace":"test"}, "namespace": "test", "name": "dc1", "reconcileID": "1e084c00-439c-440c-855d-3b7b83e187d2", "error": "Service \"cluster1-dc1-node-port-service\" is invalid: spec.ports[0].nodePort: Invalid value: 7000: provided port is not in the valid range. The range of valid ports is 30000-32767"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235
2024-11-29T11:35:04.073Z        DEBUG   events  Service "cluster1-dc1-node-port-service" is invalid: spec.ports[0].nodePort: Invalid value: 7000: provided port is not in the valid range. The range of valid ports is 30000-32767   {"type": "Warning", "object": {"kind":"CassandraDatacenter","namespace":"test","name":"dc1","uid":"0d32a203-d105-4579-860e-69b7708cfe12","apiVersion":"cassandra.datastax.com/v1beta1","resourceVersion":"194401363"}, "reason": "ReconcileFailed"}


###cassdc.yaml
```
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
  namespace: test
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: "4.1.2"
  managementApiAuth:
   insecure: {}
  networking:
    nodePort:
      native: 30046
  size: 3
  storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: storage-rwo-ext4-retain
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  podTemplateSpec:
    spec:
      containers:
        - name: "cassandra"
      securityContext: {}
  resources:
    requests:
      memory: 6Gi
      cpu: 500m
    limits:
      memory: 8Gi
      cpu: 800m
  config:
    jvm-server-options:
      initial_heap_size: "800m"
      max_heap_size: "800m"
    cassandra-yaml:
      file_cache_size_in_mb: 100
      memtable_space_in_mb: 100
```

unfortunately no luck with this type of configuration.

is it because I use the cass-operator only, not the full k8ssandra stack?

**Comment by burmanm** [comment]
The port 7000 is from missing internode setting. So in the networking, you need to have both internode and native set.

**Comment by phillowAT** [comment]
meaning i need to set then all ports to be on nodeport, or just to set them in general?

**Comment by phillowAT** [comment]
ignore above, let me test first :)

**Comment by phillowAT** [comment]
Hi burmann,

thanks for the final hint, nodeport is now working with:
```
  networking:
    nodePort:
      native: 30046
      internode: 30047
```
for this test. :)
The only thing I cannot figure out yet is how to configure "USE_HOST_IP_FOR_BROADCAST: true". I'm hoping you could also give me a hint. All the nodeport cfg does not mean much as long as the broadcast ip´s aren´t set to the host-IPs for the client to connect to them all

**Comment by burmanm** [comment]
I'm unsure what you mean with that. In my example the pod has correctly set this:

```yaml
    - name: USE_HOST_IP_FOR_BROADCAST
      value: "true"
```

**Comment by burmanm** [comment]
And if I check the configs, it shows it correctly also for Cassandra:

```console
[cassandra@cluster2-dc2-r1-sts-0 config]$ grep 172 *
cassandra.yaml:broadcast_rpc_address: 172.18.0.8
[cassandra@cluster2-dc2-r1-sts-0 config]$ ip addr | grep eth0
11: eth0@if12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65535 qdisc noqueue state UP group default 
    inet 10.244.4.3/24 brd 10.244.4.255 scope global eth0
[cassandra@cluster2-dc2-r1-sts-0 config]$
```

That said, without having hostNetwork enabled (under networking), my Pod does not have access to bind to that IP.

**Comment by phillowAT** [comment]
Hi burmanm,
when trying to use hostnetwork with the 2 nodeports configured, I do get a lot of errors on all other ports configured (ports are still the default ones while cluster is expecting 32k highports). Is there a way to only have CQL exposed on nodeport, while all others are done with headless? In theory this should be possible, but I am not sure if the operator supports that.

sorry for dragging it further and thank you for your efforts and testing

**Comment by phillowAT** [comment]
Hi burmanm,
with:
```
  networking:
    nodePort:
      native: 30046
      internode: 30047
```
We were able to connect from an external client, as the rpc_address is mapped to the host IPs, yay!!!
-> There was no need to configure spec.networking.hostNetwork: true, which also would have brought a lot other complications to it as it would map all ports to nodeport.
