### ISSUE TITLE
Cannot turn off `rpc_keepalive` and `auto_snapshot` using the `spec.config.cassandra-yaml`

### ISSUE THREAD

**Issue by kos-team** [k8ssandra/cass-operator#772]
### What happened?

After deploying a Cassandra cluster with rpc_keepalive set to false and auto_snapshot set to false, these two features still appear enabled in the runtime configuration (set to `true` in system_views.settings).

### What did you expect to happen?

We expect that the runtime configurations used by Cassandra match the `cassandra-yaml` we provided in the CR.

### How can we reproduce it (as minimally and precisely as possible)?

1. deploy a cluster with `rpc_keepalive: false` and `auto_snapshot: false`, for example:
```
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: test-cluster
spec:
  clusterName: development
  serverType: cassandra
  serverVersion: "4.1.2"
  managementApiAuth:
    insecure: {}
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  resources:
    requests:
      memory: 2Gi
      cpu: 1000m
  racks:
    - name: rack1
    - name: rack2
    - name: rack3
  config:
    cassandra-yaml:
      num_tokens: 16
      authenticator: PasswordAuthenticator
      authorizer: CassandraAuthorizer
      role_manager: CassandraRoleManager
      auto_snapshot: false
      rpc_keepalive: false
```
2. exec into one pod and query the system variables using `cqlsh -r {user} -p {password} -e "SELECT (name,value) FROM system_views.settings where name = 'rpc_keepalive'"`

### cass-operator version

latest

### Kubernetes version

1.31.0

### Method of installation

Kustomize

### Anything else we need to know?

The environment variable `CONFIG_FILE_DATA` in `server-config-init` (one of the init containers) contains the correct configuration: `auto_snapshot: false`. However, in the `config/cassandra.yaml` file, `auto_snapshot` is still enabled. We suspect that there may be a marshaling issue when generating the configuration file `cassandra.yaml` inside `server-config-init`.
