### ISSUE TITLE
ScheduledTasks API is broken in several ways

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/cass-operator#792]
### What happened?

The ScheduledTasks CRD doesn't correctly inline the CassandraTaskSpec due to a missing comma:
```
type TaskDetails struct {
	// Name of the task. Always populated.
	Name string `json:"name,omitempty"`
	// +inline
	CassandraTaskSpec `json:"omitempty"`
}
```

Hence the expected name for it is currently `omitempty`.

When passing this name to get the CR created, the controller will panic:
```
2025-05-23T13:52:06.454Z	ERROR	Observed a panic	{"controller": "scheduledtask", "controllerGroup": "control.k8ssandra.io", "controllerKind": "ScheduledTask", "ScheduledTask": {"name":"example-scheduled-task","namespace":"cass-operator"}, "namespace": "cass-operator", "name": "example-scheduled-task", "reconcileID": "6d9d10e2-df5f-4fa4-b033-7b4f66e19482", "panic": "runtime error: invalid memory address or nil pointer dereference", "panicGoValue": "\"invalid memory address or nil pointer dereference\"", "stacktrace": "goroutine 272 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x1de6be8, 0x4000a574a0}, {0x17be0c0, 0x2e6b720})\n\t/go/pkg/mod/k8s.io/apimachinery@v0.31.7/pkg/util/runtime/runtime.go:107 +0x98\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:105 +0xf0\npanic({0x17be0c0?, 0x2e6b720?})\n\t/usr/local/go/src/runtime/panic.go:791 +0x124\ngithub.com/k8ssandra/cass-operator/internal/controllers/control.(*ScheduledTaskReconciler).Reconcile(0x4000064040, {0x1de6be8, 0x4000a574a0}, {{{0x4000dd0110, 0xd}, {0x4000d06030, 0x16}}})\n\t/workspace/internal/controllers/control/scheduledtask_controller.go:101 +0x490\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0x4000a57410?, {0x1de6be8?, 0x4000a574a0?}, {{{0x4000dd0110?, 0x0?}, {0x4000d06030?, 0x0?}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:116 +0x9c\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x1dfef00, {0x1de6c20, 0x40003d2000}, {{{0x4000dd0110, 0xd}, {0x4000d06030, 0x16}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:303 +0x2b0\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x1dfef00, {0x1de6c20, 0x40003d2000})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:263 +0x18c\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:224 +0x80\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 112\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:220 +0x418\n"}
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:917
github.com/k8ssandra/cass-operator/internal/controllers/control.(*ScheduledTaskReconciler).Reconcile
	/workspace/internal/controllers/control/scheduledtask_controller.go:101
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:116
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:303
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:224
2025-05-23T13:52:06.455Z	ERROR	Reconciler error	{"controller": "scheduledtask", "controllerGroup": "control.k8ssandra.io", "controllerKind": "ScheduledTask", "ScheduledTask": {"name":"example-scheduled-task","namespace":"cass-operator"}, "namespace": "cass-operator", "name": "example-scheduled-task", "reconcileID": "6d9d10e2-df5f-4fa4-b033-7b4f66e19482", "error": "panic: runtime error: invalid memory address or nil pointer dereference [recovered]"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:224
```

### What did you expect to happen?

The struct should be correctly inlined and the controller shouldn't panic.

### How can we reproduce it (as minimally and precisely as possible)?

This won't be accepted:

```
apiVersion: control.k8ssandra.io/v1alpha1
kind: ScheduledTask
metadata:
  labels:
    app.kubernetes.io/name: cass-operator
    app.kubernetes.io/managed-by: kustomize
  name: scheduledtask-sample
  namespace: cass-operator
spec:
  schedule: "*/1 * * * *"
  taskDetails:
    name: "my-task"
    datacenter:
      name: dc1
      namespace: cass-operator
    jobs:
      - name: gc
        command: garbagecollect
        args:
          pod_name: cluster1-dc1-r2-sts-0
```

This will panic:
```
apiVersion: control.k8ssandra.io/v1alpha1
kind: ScheduledTask
metadata:
  name: example-scheduled-task
  namespace: cass-operator
  labels:
    my-label: test
  annotations:
    myannotation: testannotation
spec:
  schedule: "* * * * *"
  taskDetails:
    name: "my-task"
    omitempty:
      datacenter:
        name: dc2
        namespace: cass-operator
      jobs:
        - name: gc
          command: garbagecollect
```

### cass-operator version

1.24.0

### Kubernetes version

1.30

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/CASS-107) by [Unito](https://www.unito.io)
┆Issue Number: CASS-107
